.TH wameku_daemon 1 "APR 3 2013" "Bradley Smith"
.SH NAME
wameku_daemon \- a daemon that listens for DRb calls to report system info back to the mothership
.SH SYNOPSIS
.B wameku_daemon
.BR [string]
.PP
.SH DESCRIPTION
A daemon that reports system information via plugins back to the mothership
.PP
.SH AUTHOR
.TP
Bradley Smith <bradleydsmith@gmail.com>
